#if defined __cplusplus
#include <memory>
#include <numeric>

#define _USE_MATH_DEFINES
#include <math.h>

#include <QObject>
#include <QFile>
#include <QAudioInput>
#include <QAudioDeviceInfo>
#include <QVector>
#include <QDateTime>
#include <QDebug>
#include <QDialog>
#include <QLineEdit>
#include <QDir>
#include <QFileDialog>
#include <QMessageBox>
#include <QMetaObject>
#include <QtEndian>
#include <QCryptographicHash>
#include <QApplication>
#include <QMainWindow>
#include <QVBoxLayout>
#include <QScrollArea>
#include <QSlider>
#include <QListWidget>
#include <QWidget>
#include <QSplitter>
#include <QTextBrowser>
#include <QScrollBar>
#include <QMenuBar>
#include <QSignalMapper>
#include <QActionGroup>
#include <QSettings>
#include <QFormLayout>
#include <QSpinBox>
#include <QDialogButtonBox>
#include <QDesktopServices>
#include <QTcpServer>
#include <QTcpSocket>
#include <QSet>
#include <QLabel>
#include <QTimer>
#include <QPainter>
#include <QStyledItemDelegate>
#include <QListWidgetItem>
#include <QFontMetrics>
#include <QThreadPool>
#include <QRunnable>
#endif
